### ISSUE TITLE
Tutorials missing

### ISSUE THREAD

**Issue by owensgl** [ikwak2/aSPU#3]
Hi,

The tutorials are leading to a dead website. Seems like something happened to your web hosting.

**Comment by ikwak2** [comment]
Hi Gregory,

I was hosting my personal website through university of Minnesota.
Recently, I changed my job, and I can not use that domain.
Do you know easy way to upload some of my tutorials (html files) and link
them to that url?
I may need to study some infra structure that I can use (github also
provide some of them? )

Thanks a lot!
Sincerely,
Andy

2017-12-12 7:45 GMT+09:00 Gregory Owens <notifications@github.com>:

**Comment by zx8754** [comment]
Any update on this?

Maybe related https://github.com/ikwak2/aSPU_tutorials/issues/1

**Comment by ikwak2** [comment]
Just updated!
